name: "Continuous Integration"

on: [push, pull_request]

jobs:
  unittest:
    name: "Run the unit-tests"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "8.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          tools: "composer:v2"
          php-version: "${{ matrix.php-version }}"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
         echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: "Install dependencies"
        if: "matrix.php-version != '8.0'"
        run: "composer install --no-interaction --no-progress --prefer-dist"

      - name: "Install dependencies ignoring PHP requirement"
        if: "matrix.php-version == '8.0'"
        run: "composer update --no-interaction --no-progress --prefer-dist --ignore-platform-req=php"

      - name: "Run the unit-tests"
        run: "composer ut"

  fulltest:
    name: "Run all tests (7.4)"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          tools: composer:v2, composer-normalize
          php-version: "7.4"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --prefer-dist"

      - name: "Run all tests"
        run: "composer test"

      - name: "Normalize composer.json"
        run: "composer-normalize --dry-run --no-check-lock --no-update-lock"
