name: "Continuous Integration"

on:
  push:
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.github/workflows/sonar.yml'
      - 'LICENSE'
      - 'scripts/**'
      - 'sonar-project.properties'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.github/workflows/sonar.yml'
      - 'LICENSE'
      - 'scripts/**'
      - 'sonar-project.properties'
  # Allow manually triggering the workflow
  workflow_dispatch:

jobs:
  unittest:
    name: "Run the unit-tests"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.1"
        phpunit-args: ""
        include:
          - php-version: "8.0"
            phpunit-args: "--order-by random"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          ini-values: "error_reporting=E_ALL, display_errors=On"
          tools: "composer:v2"
          php-version: "${{ matrix.php-version }}"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
         echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --prefer-dist"

      - name: "Run the unit-tests"
        run: "composer ut -- ${{ matrix.phpunit-args }}"

  fulltest:
    name: "Run all tests (8.0)"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          ini-values: "error_reporting=E_ALL, display_errors=On"
          tools: composer:v2, composer-normalize
          php-version: "8.0"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --prefer-dist"

      - name: "Run all tests"
        run: "composer test"

      - name: "Normalize composer.json"
        run: "composer-normalize --dry-run --no-check-lock --no-update-lock"
